Add kernel sources install

diff --git a/debian-config-jobs b/debian-config-jobs
--- a/debian-config-jobs
+++ b/debian-config-jobs
@@ -163,6 +163,25 @@ function jobs ()
 
 
 
+	#
+        # Install kernel source
+        #
+        "Source" )
+                if ! is_package_manager_running; then
+                        if [[ -n $(dpkg -l | grep $SOURCE_PKG) ]]; then
+                                        debconf-apt-progress -- apt-get -y purge ${SOURCE_PKG}
+					# cleanup
+		                        debconf-apt-progress -- apt -y autoremove
+                        else
+                                        debconf-apt-progress -- apt-get -y install ${SOURCE_PKG}
+					dialog --colors --backtitle "$BACKTITLE" --no-collapse --title " Kernel source " --clear --msgbox "\nYou will find compressed kernel source and configuration in /usr/src" 7 72
+                        fi
+                fi
+        ;;
+
+
+
+
 	# Toggle mini and full firmware
 	#
 	"Full"|"Mini" )
